---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ahmadza3/kondanganvirtual.com/
    - /bin/cp -R AlexaTomyWedding $DEPLOYPATH
    - /bin/cp -R AlexaTomyAkad $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
